#!/usr/bin/env bash
# This script ensures that Nginx is installed, running, and serving a "Hello World!" page.

apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Hello World!" > /var/www/html/index.html'
service nginx start
