#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.


sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown $USER:USER /etc/haproxy/haproxy.cfg

echo "
frontend jaggersbutchery
    bind *:80
    mode http
    default_backend app

backend app
    balance roundrobin
    server 480629-web-01 35.174.176.31:80 check
    server 439003-web-02 100.25.47.119:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
