#!/usr/bin/env bash
# script that displays To infinity and beyond indefinitely.
# In between each iteration of the loop, a sleep 2 is added

name="To infinity and beyond"

while true; do
	echo "$name"
	sleep 2
done
