#!/usr/bin/env bash
#  script that displays:
# To infinity and beyond indefinitely With a sleep 2 in between each iteration.

name="To infinity and beyond"

while true; do
	echo "$name"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
