#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd, it only displays
# username, user id, and home directory path for user.

input_file="/etc/passwd"

while IFS=":" read -r username _  uid _ homedir _; do
	echo "Username: $username"
	echo "User ID: $uid"
	echo "Home directory: $homedir"
	echo "--------------------------"
done < "$input_file"
