#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd, using the while
# loop + IFS.

input_file="/etc/passwd"


while IFS=":" read -r username password uid gid gecos homedir shell; do
	echo "The user $username is part of the $gid gang,"\
	"lives in $homedir and rides $shell."\
	"$uid's place is protected by the passcode $password,"\
	"more info about th user here: $gecos"
done < "$input_file"
