#!/usr/bin/env bash
# Script that configures an Ubuntu server with the below requirements.
# localhost resolves to 127.0.0.2 and facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/file.new

echo "127.0.0.2 localhost" > ~/file.new

echo "8.8.8.8 facebook.com" >> ~/file.new

cp -f ~/file.new /etc/hosts
