#!/usr/bin/env bash
# Run Nginx as Nginx
# With this cofiguration, if a hacker does find a security issue that allows them to break-in to my server, the impact is limited by the permissions of the nginx user.

sudo sed -i 's/user www-data/user nginx' /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
